const langArr = {
	"rating": {"ru": "Рейтинг",
	"en": "Rating",
	"ua": "Рейтинг",
	},
	"title-settings": {"ru": "Chess настройки",
	"en": "Chess Settings",
	"ua": "Chess налаштування",
	},
	"settings": {"ru": "Настройки",
	"en": "Settings",
	"ua": "Налаштування",
	},
	"title-game": {"ru": "Игра в шахмати",
	"en": "Chess game",
	"ua": "Гра в шахи",
	},
	"play": {"ru": "Играть",
	"en": "Play",
	"ua": "Грати",
	},
	"title-home": {"ru": "Главная",
	"en": "Home",
	"ua": "Головна",
	},
	"home": {"ru": "Домой",
	"en": "Home",
	"ua": "Додому",
	},
	"title-developers": {"ru": "Разработчики",
	"en": "Developers",
	"ua": "Розробники",
	},
	"developers": {"ru": "Разработчики",
	"en": "Developers",
	"ua": "Розробники",
	},
	"title-help": {"ru": "Помощь",
	"en": "Help",
	"ua": "Допомога",
	},
	"help": {"ru": "Помощь",
	"en": "Help",
	"ua": "Допомога",
	},
	"title-rules": {"ru": "Правила",
	"en": "Rules",
	"ua": "Правила",
	},
	"rules": {"ru": "Правила",
	"en": "Rules",
	"ua": "Правила",
	},
	"title-chat": {"ru": "Чат",
	"en": "Chat",
	"ua": "Чат",
	},
	"chat": {"ru": "Чат",
	"en": "Chat",
	"ua": "Чат",
	},
	"language": {"ru": "Язык",
	"en": "Language",
	"ua": "Мова",
	},
	"profile": {"ru": "Профиль:",
	"en": "Profile:",
	"ua": "Профіль:",
	},
	"name": {"ru": "Имя",
	"en": "Name",
	"ua": "Ім'я",
	},
	"surname": {"ru": "Фамилия",
	"en": "Surname",
	"ua": "Фамілія",
	},
	"fair-play-policy": {"ru": "Правила честной игры",
	"en": "Fair Play Policy",
	"ua": "Правила чесної гри",
	},
	"rules-list": {"ru": "<li>Все ваши ходы должны быть вашими собственными.</li><li>Ни в коем случае не жульничайте.</li><li>Не обращайтесь за помощью к другим лицам, включая родителей, друзей, тренеров или других игроков.</li><li>Не используйте шахматные движки, программное обеспечение любого рода, ботов, плагины или любые инструменты, которые анализируют позиции во время игры.</li><li>Не выполнять никакого автоматического анализа или «проверка грубых ошибок» в ваших играх</li><li>Не позволяйте никому использовать вашу учетную запись.</li><li>Не используйте чужую учетную запись.</li><li>Не манипулируйте рейтингами искусственно , матчи или результаты игры.</li><li>Не вмешивайтесь в игровой процесс других участников</li><li>Подозрение оппонента в использовании посторонней помощи не является оправданием для того, чтобы делать то же самое Если вы подозреваете, что кто-то жульничает, сообщите об этом игроке на Chess.</li>",
	"en": "<li>All of your moves must be your own.</li><li>Do not cheat in any way.</li><li>Do not get help from any other person, including parents, friends, coaches or another player.</li><li>Do not use chess engines, software of any kind, bots, plugins or any tools that analyze positions during play.</li><li>Do not perform any automated analysis or “blunder checking” of your games in progress.</li><li>Do not allow anyone else to use your account</li><li>Do not use anyone else's account.</li><li>Do not artificially manipulate ratings, matches, or game outcomes.</li><li>Do not interfere with the gameplay of other members.</li><li>Suspecting your opponent of using outside help is not an excuse to do the same If you suspect someone is cheating, report the player to Chess.</li>",
	"ua": "<li>Усі ваші рухи мають бути вашими власними.</li><li>У жодному разі не обманюйте.</li><li>Не звертайтеся за допомогою від будь-якої іншої особи, включаючи батьків, друзів, тренерів чи іншого гравця.</li><li>Не використовуйте шахові механізми, будь-яке програмне забезпечення, ботів, плагіни чи будь-які інструменти, які аналізують позиції під час гри.</li><li>Не виконуйте жодного автоматичного аналізу чи «перевірки помилок» ваших ігор, що виконуються.</li><li>Не дозволяйте іншим використовувати ваш обліковий запис.</li><li>Не використовуйте чужий обліковий запис.</li><li>Не маніпулюйте штучно рейтингами, матчами чи результатами гри.</li><li>Не втручайтеся в гру інших учасників</li><li>Підозра вашого опонента у використанні сторонньої допомоги не є приводом робити те саме Якщо ви підозрюєте, що хтось обманює, повідомте про гравця на Chess.</li>"
	},
	"analyze": {"ru":"Анализ",
	"en":"Analyze",
	"ua": "Аналіз"
	}
}